# Do we want to send players a message when they are reconnected to a server?
message-on-reconnect: true
reconnect-message:
  - "&7You were reconnected to &f%server%&7."

# Do we want to send a message when their previous server isn't available?
not-available: true
not-available-message:
  - "&7Unable to reconnect you to your last server."

###################### STORAGE
# Default: "yaml"
# Options:
#   - "mysql" <- Remote or Local SQL database
#   - "yaml" <- Local .yml file
#   - "sqlite" <- Local SQL database
storage:
  method: "yaml"
  # The below is only needed if you are using MySQL
  data:
    address: localhost
    database: reconnect
    username: root
    password: ''
